### ISSUE TITLE
How do I create a IMA user for SimpleDB

### ISSUE THREAD

**Issue by madsbrydegaard** [rexm/SimpleDb.Net#35]
Great work on the wrapper - works splendid!

However I just spent a lot of time figuring how to get a public/private key set working for AWS since they disabled the default key pair for root user.

I had to create a new user and grant admin rights since theres no managed policy for SimpleDB.
Or have I overlooked something?

Thnx

**Comment by rexm** [comment]
See here for how to use IAM to create SimpleDB policies: http://docs.aws.amazon.com/AmazonSimpleDB/latest/DeveloperGuide/UsingIAMWithSDB.html
