### ISSUE TITLE
Querying with orderby without a where clause throw an error

### ISSUE THREAD

**Issue by madsbrydegaard** [rexm/SimpleDb.Net#36]
```
var items = from item in simpleDb.Domains["myDomain"].Items
              //where item["Status"] == "Hot" && item["LastUpdated"] > DateTime.Now.AddDays(-1)
              orderby item["LastUpdated"] descending
              select item;
```

**Comment by rexm** [comment]
What is the error?

**Comment by rexm** [comment]
Actually I think I know this issue. This is a limitation of SimpleDB itself - it is not allowed to include an attribute in the OrderBy clause if that attribute is also not present in the predicate clause.

I've considered making the library handle that internally by automatically adding something like a where not null clause if the attribute isn't already in the predicate. But that's silently adding a predicate, so not sure if that's desired all the time.

**Comment by madsbrydegaard** [comment]
I think you are right. No error text was returned from Amazon...
